### ISSUE TITLE
publish package to public registry

### ISSUE THREAD

**Issue by gpolitis** [jitsi/sdp-interop#1]

**Comment by hamidyaseen** [comment]
Hi politis, can you please publish this package? because I am trying to install it but no success... I have also tried like as
npm install git+https://git@github.com/jitsi/sdp-interop.git 
or can you help how to install it ?

**Comment by gpolitis** [comment]
I'll try to do that later today. About not being able to install the module, maybe your npm version is old? This should work with a reasonably recent npm:

```
"dependencies": {
      "sdp-interop": "jitsi/sdp-interop#f65fedfe57a",
},
```

**Comment by hamidyaseen** [comment]
Thanks a lot if you can manage today... I just yesterday install NodeJS and has npm version is 2.7.4.
and if you like to see the log message is 
C:\Users\Administrator\Documents\Visual Studio 2013\Projects\VW5NodeApp\VW5NodeApp>npm install sdp-interop
npm WARN package.json vw5NodeApp@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "
nstall" "sdp-interop"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Cannot read property 'trim' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\Documents\Visual Studio 2013\Projects\VW5NodeApp\VW5NodeApp\npm-debug.log

**Comment by gpolitis** [comment]
https://www.npmjs.com/package/sdp-interop

**Comment by hamidyaseen** [comment]
Thanks
