### ISSUE TITLE
ssrc attributes for recvonly m-sections in unified-plan

### ISSUE THREAD

**Issue by benbro** [jitsi/sdp-interop#11]
Firefox recently started adding ssrc attributes for recvonly m-sections
https://bugzilla.mozilla.org/show_bug.cgi?id=1160280

Chrome doesn't send SSRC in recvonly m-section.

How can the the module handle this when trying to convert plan-B to unified-plan with recvonly m-sections?

**Comment by gpolitis** [comment]
Hi @benbro, you can set an SSRC yourself by mungling the SDP and Chrome will pick it up.

**Comment by benbro** [comment]
I meant that if the server is using plan-b, some of the information might be lost when translating to unified-plan like recvonly ssrc in m-sections.

I'll close it for now and reopen if I'll run into a problem.
