### ISSUE TITLE
Client side use

### ISSUE THREAD

**Issue by NTShop** [jitsi/sdp-interop#22]
Is it possible to get this module loaded into the client side? 

I've tried packing it up using both browserify and webpack and they both do create a .js file (for example: interop.js) 

`./node_modules/.bin/webpack node_modules/sdp-interop/lib/index.js public/interop.js`

I can load the interop.js script (created by browserify or webpack) into the browser using a script tag and node/express do deliver it into browser no problem. However that doesn't seem to get the Interop() object exported into browser's space. If I try something like "var abc = new Interop()" that totally fails with "Interop is undefined" or similar (I don't remember the exactly wording, that's the gist of it). 

Am I approaching this totally wrong? Or did I miss something? I'd like to get it into browser space so that I don't have to totally rewrite my server.js and client.js code (I'm adding a new feature and that feature requires negotiation that fails due to the UnifiedPlan - PlanB incompatibility issues. Otherwise without my new features RTC between the browser does work. But, I gotta add the feature.

Anyone have pointers? Thanks in advance for help.

**Comment by gpolitis** [comment]
Have you tried requiring the sdp-interop from your client code?

Regardless, even if you were able to include the library in your client, you're probably going to stumble upon other issues, notably this one https://github.com/jitsi/sdp-interop/issues/4

**Comment by NTShop** [comment]
I'm a rookie when it comes to getting nodejs modules into a browser. That's the overall problem I face, that I can't seem to get sdp-interop available in the browser. Got any tips on how I can do that? Browsers don't have a native "require" function, so I can't require it that way. Unless I'm missing something? Or maybe I misunderstand how to use sdp-interop (are there docs available to assist that I overlooked? I'm a long time dev, but somewhat new to node).

Or how would I go about getting it to work via nodejs given that the example code shown at the URL below looks at the navigator object to detect the browser - which isn't available to node? 

Also is there any simple web demo page out there on the net that uses sdp-interop that I can land on and test for myself? 

@gpolitis - how do you personally implement it in general? There's that "navigator" object use in detecting a browser (as seen at the URL below), which makes me think it's supposed to be a client-side issue since node has no awareness of the client browser via a "navigator" object.

https://hacks.mozilla.org/2015/06/firefox-multistream-and-renegotiation-for-jitsi-videobridge/

For what it's worth, right now I always have Chrome making the initial offer since that's the spec for sdp-interop. This is fine with me because I have an app where a host user controls all initiating all calls and I mandate the use of Chrome for the host user (these calls are audio-only).

If you're interested, here's what I'm doing: I use a signaling server running on node for an **audio-only** chat that takes place. There's always a "chat host user" that controls the audio chat, and in addition to talking the host may or may not decide to play an audio clip which the host and RTC peers hear (this is a new feature I'm trying to add) - therefore when the host grants access to their mic the host's client side JS adds an additional track to the hosts audiocontext [via createMediaStreamDestination() and addTrack() ] and that track is used to pipe in any audio clip the host decides to play (if any), this way the audio clip goes into the host's mic stream and out to anyone connected to the host via RTC. So... anyone can request to be called to talk to the host. BUT, if the host has not connected to signaling server yet then any requesting wanna-be peers simply sit in a data channel queue via the signaling server (in other words, a potential peer says "I'm on the queue list, I want you to call me"). When the host connects to the server the host then sees a list of wanna-be RTC peers in the queue. The host must selectively click on a specific wannabe-peer which initiates the RTC peer connections. This works fine with Chrome to Chrome and with FF to FF, but Chrome to FF fails (because of the extra track in the host's audio context) and if I remove the code that adds the extra audio track then Chrome to FF works and FF to Chrome works (e.g. the RTC connections all work, it's the extra track that breaks cross browser connections). And that is why I'm trying to integrate sdp-interop, because when that extra track is part of the hosts stream then Chrome initiating a call to FF fails.

**Comment by gpolitis** [comment]
I read your use case and I think it makes sense to use sdp-interop.

When you pack a library with browserify or webpack everything is put inside a closure so that the global space (the window) is not polluted (that's why var abc = new Interop() fails). You can either write a module that exposes Interop in the global space (the window) or write your JS code in node modules and compile it with browserify or webpack.

In any case, I don't think this is an issue with sdp-interop, rather with how you're setting up your project, so I'll close this issue for now. Please come back if you have questions about sdp-interop specifically.

**Comment by NTShop** [comment]
You're probably right. I came up with a different way of handling the issue so I don't need sdp-interop. Thank for your advice, may be helpful in the future.

**Comment by vivekdoshi2** [comment]
Any one have idea how to use this from the client side ?
