### ISSUE TITLE
support the case where FF is the offerer

### ISSUE THREAD

**Issue by gpolitis** [jitsi/sdp-interop#4]

**Comment by stiv-yakovenko** [comment]
var description ={sdp: [
"v=0",
"o=mozilla...THIS_IS_SDPARTA-47.0.2 5854479983320605816 0 IN IP4 0.0.0.0",
"s=-",
"t=0 0",
"a=fingerprint:sha-256 92:50:6F:74:7D:77:36:72:C5:D3:CD:45:56:E4:CA:4C:85:FD:04:BF:F7:EB:44:E0:22:B6:71:30:A3:79:C0:C5",
"a=ice-options:trickle",
"a=msid-semantic: WMS *",
"a=group:BUNDLE audio video",
"m=audio 9 UDP/TLS/RTP/SAVPF 111",
"c=IN IP4 0.0.0.0",
"a=rtpmap:111 opus/48000/2",
"a=fmtp:111 maxplaybackrate=48000;stereo=1",
"a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level",
"a=setup:active",
"a=mid:audio",
"a=sendrecv",
"a=ice-ufrag:50e70556",
"a=ice-pwd:7c9f8b4c546cbb61e8558d930f13a35a",
"a=ssrc:2374622016 cname:{bdc6304f-a81b-49ab-8839-9ce0960a73e7}",
"a=ssrc:2374622016 msid:{ee5bd5d9-44fe-4326-a2d1-2b155cdaf7fd} {810755f1-80dc-480c-9b15-943f26de366d}",
"a=rtcp-mux",
"m=video 9 UDP/TLS/RTP/SAVPF 100",
"c=IN IP4 0.0.0.0",
"a=rtpmap:100 VP8/90000",
"a=fmtp:100 max-fs=12288;max-fr=60",
"a=rtcp-fb:100 nack",
"a=rtcp-fb:100 nack pli",
"a=rtcp-fb:100 ccm fir",
"a=setup:active",
"a=mid:video",
"a=sendrecv",
"a=ice-ufrag:50e70556",
"a=ice-pwd:7c9f8b4c546cbb61e8558d930f13a35a",
"a=ssrc:1154788772 cname:{bdc6304f-a81b-49ab-8839-9ce0960a73e7}",
"a=ssrc:1154788772 msid:{ee5bd5d9-44fe-4326-a2d1-2b155cdaf7fd} {1a16a697-3584-467c-8a21-dc0d33703d78}",
"a=rtcp-mux"
].join("\n"),type:"answer"};
interop.toUnifiedPlan(description);

If I launch it on Mozilla, I get this error: An unmapped SSRC was found.
Can anyone comment this?

**Comment by gpolitis** [comment]
https://github.com/jitsi/sdp-interop/pull/30 fixes this
